inferenceExtension:
  replicas: 1
  image:
    name: epp
    hub: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension
    tag: main
    pullPolicy: Always
  extProcPort: 9002
  env: []
  pluginsConfigFile: "default-plugins.yaml"
  # Define additional container ports
  extraContainerPorts: []
  # Define additional service ports
  extraServicePorts: []

  # This is the plugins configuration file.
  # pluginsCustomConfig:
  #   custom-plugins.yaml: |
  #     apiVersion: inference.networking.x-k8s.io/v1alpha1
  #     kind: EndpointPickerConfig
  #     plugins:
  #     - type: custom-scorer
  #       parameters:
  #         custom-threshold: 64
  #     schedulingProfiles:
  #     - name: default
  #       plugins:
  #       - pluginRef: custom-scorer

  # Example environment variables:
  # env:
  #   ENABLE_EXPERIMENTAL_FEATURE: "true"

  flags:
    # Log verbosity
    - name: v
      value: 1

  affinity: {}

  tolerations: []

  # Monitoring configuration for EPP
  monitoring:
    interval: "10s"
    # Prometheus ServiceMonitor will be created when enabled for EPP metrics collection
    prometheus:
      enabled: false
      auth:
        enabled: true
        # Service account token secret for authentication
        secretName: inference-gateway-sa-metrics-reader-secret
      # additional labels for the ServiceMonitor
      extraLabels: {}

    # DEPRECATED: The 'gke' configuration will be removed in the next release.
    gke:
      enabled: false
  tracing:
    enabled: false
    otelExporterEndpoint: "http://localhost:4317"
    sampling:
      sampler: "parentbased_traceidratio"
      samplerArg: "0.1"

inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm # vllm, triton-tensorrt-llm
  # modelServers: # REQUIRED
  #   matchLabels:
  #     app: vllm-llama3-8b-instruct

# Options: ["gke", "istio", "none"]
provider:
  name: none

  # GKE-specific configuration.
  # This block is only used if name is "gke".
  gke:
    # Set to true if the cluster is an Autopilot cluster.
    autopilot: false

istio:
  destinationRule:
    # Provide a way to override the default calculated host
    host: "" 
    # Optional: Enables customization of the traffic policy
    trafficPolicy: {}
      # connectionPool:
      #   http:
      #     maxRequestsPerConnection: 256000